remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "File an issue":
    - "https://github.com/PacificBiosciences/pbbioconda/issues/new?template=bug_report.md"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

color_scheme: custom

# Footer content
# appears at the bottom of every page's main content
footer_content: "THIS WEBSITE AND CONTENT AND ALL SITE-RELATED SERVICES, INCLUDING ANY DATA, ARE PROVIDED \"AS IS,\" WITH ALL FAULTS, WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON-INFRINGEMENT OR FITNESS FOR A PARTICULAR PURPOSE. YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THIS SITE, ALL SITE-RELATED SERVICES, AND ANY THIRD PARTY WEBSITES OR APPLICATIONS. NO ORAL OR WRITTEN INFORMATION OR ADVICE SHALL CREATE A WARRANTY OF ANY KIND. ANY REFERENCES TO SPECIFIC PRODUCTS OR SERVICES ON THE WEBSITES DO NOT CONSTITUTE OR IMPLY A RECOMMENDATION OR ENDORSEMENT BY PACIFIC BIOSCIENCES."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link


title: "Iso-Seq Docs"
tagline: "Scalable De Novo Isoform Discovery from PacBio HiFi Reads"

search_enabled: true

ga_tracking: G-SY7XDRP17G
ga_tracking_anonymize_ip: true

url: "https://isoseq.how"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
